### ISSUE TITLE
Options [-e|--environment <NAME="VALUE">] is not supported

### ISSUE THREAD

**Issue by mikoca** [joaoopereira/dotnet-test-rerun#104]
Hi,

Options [-e|--environment <NAME="VALUE">] is not supported. https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test.

Can you please add support?

Thanks.

**Comment by ricardofslp** [comment]
Hi @mikoca ,

Could you please test with this version: https://www.nuget.org/packages/dotnet-test-rerun/1.9.0-alpha.1

**Comment by ricardofslp** [comment]
Hi @mikoca ,

Did it work?

**Comment by ricardofslp** [comment]
Officially delivered in version: https://www.nuget.org/packages/dotnet-test-rerun/1.9.0
