### ISSUE TITLE
On Theory Failure all cases are being re-run

### ISSUE THREAD

**Issue by bokece** [joaoopereira/dotnet-test-rerun#106]
When a theory's subset fails then `dotnet-test-rerun` re-runs all test cases of the theory.

**Comment by ricardofslp** [comment]
Hi @bokece,

Could you please share how you normally run the tool?

**Comment by bokece** [comment]
Hello @ricardofslp and thank you for your prompt response. 

**Command:** `test-rerun $pwd\bin\Debug\net7.0\TempXunitTest.dll --rerunMaxAttempts 2`

**Only test class:** 
```
public class UnitTest1
{
    [Fact]
    public void Test1()
    {
        var result = RandomBoolProbability(100);

        Assert.True(result);
    }
    
    [Theory]
    [InlineData(1, 2, 3)]
    [InlineData(-4, -6, -10)]
    [InlineData(-2, 2, 0)]
    [InlineData(int.MinValue, -1, int.MaxValue)]
    public void Test2(int value1, int value2, int expected)
    {
        Console.WriteLine("Test: " +  value1);
        
        var _ = value1 + value2;
        var __ = expected;
        
        var result = RandomBoolProbability(100);

        Assert.True(result);
    }
    
    [Theory, MemberData(nameof(TestData)) ]
    public void Test3(TestDataNonSerialized td)
    {
        var result = RandomBoolProbability(70);

        Assert.True(result);
    }
}

```

**Actual behaviour:** 
When a test case of  a theory (e.g. Test2, Test3) fails
Then all theory's test cases are executed again on the second iteration

**Expected behaviour:** 
When a test case of  a theory (e.g. Test2, Test3) fails
Then only the failed test case is executed again on the second iteration

**Comment by ricardofslp** [comment]
Hi @bokece,

Could you please test with this version: https://www.nuget.org/packages/dotnet-test-rerun/1.9.0-alpha.1 to see if it solves the issue you were facing  ?

Thanks.

**Comment by ricardofslp** [comment]
Hi @bokece ,

Did it work?
