### ISSUE TITLE
Tests aren't re-run if verbosity is set to normal

### ISSUE THREAD

**Issue by unbuttoned** [joaoopereira/dotnet-test-rerun#149]
When using test-reun with a command like so `test-rerun <test file name> --filter "<filter>" -v normal` after the first test run, if any of the tests failed, the command exits without any re-run attempts:

![image](https://github.com/joaoopereira/dotnet-test-rerun/assets/62380573/34d566a2-a18a-41bb-9363-5acafa74b48f)

**Comment by ricardofslp** [comment]
Hi @unbuttoned ,

Thanks for reporting this. I will try to take a look into this during this week.

Thanks.

**Comment by ricardofslp** [comment]
Hi,

Had no time yet to look at this but will try to look this week.

**Comment by ricardofslp** [comment]
Hi,

Opened a pull request for this. Will try to release in the next days

**Comment by ricardofslp** [comment]
Hi @unbuttoned ,

Can you test this with version: https://www.nuget.org/packages/dotnet-test-rerun/2.0.1-alpha.1 ?
Thanks in advance

**Comment by unbuttoned** [comment]
Hello,
I can confirm it now works on 2.0.1 alpha 1, thanks!
