### ISSUE TITLE
Exit code "1" after sucessfull rerun

### ISSUE THREAD

**Issue by IgorMikhalev** [joaoopereira/dotnet-test-rerun#165]
Currently, the exit code is "1", even if the initially failed tests were run successfully during the rerun:

![image](https://github.com/joaoopereira/dotnet-test-rerun/assets/11911732/a5a0516b-0fc2-478f-a9d0-f01d6fb1a025)

It would make sense to exit with the code "0" if, in the end, all the tests ran successfully.

**UPD:** After cloning and examining the repository, I noticed that the exit code is covered by tests and should be "0" in the scenario I described above. I will try to gather additional information and update the issue accordingly.

**Comment by ricardofslp** [comment]
Hi @IgorMikhalev ,

Please do.
I will try to see also what it can be

**Comment by ricardofslp** [comment]
Hi @IgorMikhalev,

Please use version [v2.0.2](https://www.nuget.org/packages/dotnet-test-rerun/2.0.2)
