### ISSUE TITLE
Support for DataTestMethods when filtering on rerun

### ISSUE THREAD

**Issue by dotkarl** [joaoopereira/dotnet-test-rerun#42]
Hi, it's me again! First off, thanks for your previous quick fix! Unfortunately, another problem popped up when applying the filters, this time pertaining to our tests decorated with the `DataTestMethod` in MsTest:

```
Incorrect format for TestCaseFilter Missing Operator '|' or '&'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
No test matches the given testcase filter `FullyQualifiedName~SomeTest (Argument1, Argument2) in path/Application.IntegrationTests.dll
```

The problem lies with the brackets (`(` and `)`) in the fully qualified name of the test. These should be escaped in order for the filter attribute to work properly; see https://github.com/Microsoft/vstest-docs/blob/main/docs/filter.md.

Now this could be as easy as replacing `testsToRerun` on line 74 of RerunCommand.cs with `Regex.Replace(testsToRerun, @"[()]", @"\$&")`, but that implementation is pretty naive and I have some doubts whether it might break some things, e.g. when another logger is used or when a fully qualified name is wrapped in brackets (see the last example in the link above). Any way, I hope this helps in pointing to a more robust fix.

If there's anything I can help with, please let me know!

**Comment by joaoopereira** [comment]
Hi @dotkarl,
Can you please show us the filter that you used?

**Comment by dotkarl** [comment]
From the output in the Azure DevOps console (I changed the names of the tests for obvious reasons):
```
forking test /home/vsts/**/Tests/IntegrationTests/bin/**/Application.IntegrationTests.dll --filter "FullyQualifiedName~Test1 (Name,Ascending) | FullyQualifiedName~Test2 (Name,Descending) | FullyQualifiedName~Test3 (LastModifiedBy,Ascending) | FullyQualifiedName~Test4 | FullyQualifiedName~Test5 (Title,Descending) | FullyQualifiedName~Test6 (LastModifiedBy,Descending) | FullyQualifiedName~Test7 (Title,Descending) | FullyQualifiedName~Test8 | FullyQualifiedName~Test9 (2) | FullyQualifiedName~Test10 | FullyQualifiedName~Test11 | FullyQualifiedName~Test12 (Title,Ascending) | FullyQualifiedName~Test13 (CreatedBy,Ascending) | FullyQualifiedName~Test14 (1) | FullyQualifiedName~Test15 (CreatedBy,Descending) | FullyQualifiedName~Test16 | FullyQualifiedName~Test18 (Title,Ascending)" --logger "trx" --results-directory /home/vsts/work/_temp
```

**Comment by dotkarl** [comment]
I see @ricardofslp created a pull request for this issue, thanks for the hard work! 😃

**Comment by joaoopereira** [comment]
Hi,

@dotkarl sorry for the delay, we have launched an alpha version, can you please try it and give us feedback?
https://www.nuget.org/packages/dotnet-test-rerun/1.2.2-alpha.0

`dotnet tool install --global dotnet-test-rerun --version 1.2.2-alpha.0`

**Comment by ricardofslp** [comment]
Hi @dotkarl,

I think this solution will be able to work/solve your use case.
But please use the alpha version we've published just to check before we officially release it.

Thanks in advance.

**Comment by dotkarl** [comment]
Hi @joaoopereira and @ricardofslp, sorry for the tardy response -- I was at a conference for the past couple of days. Good news though: the problem seems to be fixed in the alpha version! Thanks a lot! :)
