### ISSUE TITLE
Task ends in success when tests have failed

### ISSUE THREAD

**Issue by dotkarl** [joaoopereira/dotnet-test-rerun#45]
Hi, it's me again :sweat_smile:

At the moment, when you run _dotnet-test-rerun_ in an Azure pipeline, it will always mark the running of the task as successful, even in case of a testsuite that still contains failing tests after the specified amount of reruns. 

```
Failed!  - Failed:     4, Passed:     3, Skipped:     0, Total:     7, Duration: 25 s - Application.IntegrationTests.dll (net6.0)


Finishing: Run integration tests
```

Is this, in your opinion, intended behaviour?

I would suspect that most users would expect the tool to signal failure in such a case. That would require terminating the process with ExitCode 1 instead of 0, which is what happens now. Would you agree with this assessment?

By the way, I believe the same issue now crops op when an unhandled exception is thrown from the code: it ends with ExitCode 0 and the pipeline simply carries on. 

As always, thank you for your great work on maintaining this tool, and also for your patience when handling the host of issues I keep dropping. If there's any more information you need from me, please let me know.

**Comment by ricardofslp** [comment]
Hi,

This behaviour that you've describe makes sense.
I will work on that.

Regarding the number of issues opened don't worry. 
Please keep providing feedback and thank you for helping us improve this tool.

**Comment by ricardofslp** [comment]
Hi @dotkarl,

Please test if the following alpha release solve this issue.

To install it do the following:
`dotnet tool install --global dotnet-test-rerun --version 1.3.0-alpha.2`

**Comment by dotkarl** [comment]
Hi @ricardofslp, the alpha version solves the issue. Thanks!

**Comment by dotkarl** [comment]
I stand corrected: this solves this issue but introduces a new one. 

The tool now exits with code '1' when not all the tests pass during the first run. Or, put differently, the task signals failure, even when all tests pass in the course of subsequent runs.

This is the output after rerun attempt 1/3:

```
No tests found with the Outcome Failed
Rerun attempt 2 not needed. All testes Passed.
##[error]Bash exited with code '1'.
Finishing: Run integration tests
```

I believe the expected behaviour should be as follows: if and only if there are tests failing during the last rerun, it should exit with code '1' (task failed); otherwise it should exit with code '0' (task succesful).

**Comment by dotkarl** [comment]
Should I open a new issue for this, or is it okay if I leave it here? The title of this issue is not entirely correct anymore. It should be something more along the lines of "Task ends in failure when tests pass after rerun(s)"

**Comment by ricardofslp** [comment]
I also agree with your understanding of the expected behavior. Will try to take a look today to this and release a new alpha version

**Comment by dotkarl** [comment]
Thanks for the quick response!

**Comment by ricardofslp** [comment]
Hi @dotkarl,

Please check the new alpha we've released with the fix. 
Let us know if it works as it should now. We'll release an official fix version if everything is ok.

`dotnet tool install --global dotnet-test-rerun --version 1.3.1-alpha.0`

**Comment by dotkarl** [comment]
Hi @ricardofslp, the issue seems to be fixed, thank you! :)
