### ISSUE TITLE
how to enable code coverage with release configuration setup

### ISSUE THREAD

**Issue by nreddipalle** [joaoopereira/dotnet-test-rerun#50]
I am trying to run this dotnet test command using this wrapper command but it seems some options doesn't work especially code coverage

dotnet test C:\a\1\s\UnitTests\UnitTests.csproj --logger trx --results-directory C:\a\_temp --configuration Release --no-build --verbosity minimal --filter (TestCategory!=DataWarehouse&TestCategory!=Integration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=C:\a\_temp\TestResults\Coverage\UnitTests-TestResults.opencover.xml

what is the equivalent command for above using test-rerun. Thanks.

**Comment by joaoopereira** [comment]
Hi @nreddipalle,

Thanks for your issue!

Currently we don't support all the options of `dotnet test`, we will check how we can add the option that you need.

Anyway, we've recently added an option to collect coverage but it is still only in an alpha. In the way we've it right now you could do it with --collect "XPlat Code Coverage".

Please try with this alpha version and let us know if it works for you: [https://www.nuget.org/packages/dotnet-test-rerun/1.4.0-alpha.0](https://www.nuget.org/packages/dotnet-test-rerun/1.4.0-alpha.0)

**Comment by ricardofslp** [comment]
Hi @nreddipalle,

Please check version 1.4.0 (https://www.nuget.org/packages/dotnet-test-rerun/1.4.0) that has already included this.
Please let us know if it works.

Thanks in advance.

**Comment by ricardofslp** [comment]
Hi @nreddipalle,

Please try again with version https://www.nuget.org/packages/dotnet-test-rerun/1.4.0

Regrading the command the equivalent would be:
test-rerun C:\a\1\s\UnitTests\UnitTests.csproj --logger trx --results-directory C:\a_temp --no-build --filter (TestCategory!=DataWarehouse&TestCategory!=Integration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=C:\a_temp\TestResults\Coverage\UnitTests-TestResults.opencover.xml

verbosity and configuration are currently not supported.

Please let us know the outcome.

**Comment by LMSSonos** [comment]
@ricardofslp wanted to test your PR with the `--configuration` but after some testing i found out, that it has not yet been released on nuget, right?

**Comment by joaoopereira** [comment]
That's correct @LMSSonos, but give me some minutes, I will publish an alpha

**Comment by joaoopereira** [comment]
done
https://www.nuget.org/packages/dotnet-test-rerun/1.5.0-alpha.0

**Comment by LMSSonos** [comment]
the `--configuration` works as expected
many thanks!!

**Comment by ricardofslp** [comment]
This has been released in version v1.5.0
Will close this ticket now. Please reopen if it does not work
