### ISSUE TITLE
Feature request: Search for all Projects

### ISSUE THREAD

**Issue by LMSSonos** [joaoopereira/dotnet-test-rerun#60]
when running `dotnet test` without a path/project it will search for all projects within the current and childfolders for test projects. This is handy so when new test-projects are added, they are found automatically. Would be awesome if `test-rerun [somepathtodll] [OPTIONS]` the `somepathtodll` would be optional

Thanks for great piece of software!

**Comment by LMSSonos** [comment]
Hi @ricardofslp 

They are connected through a solution. And you are right, `dotnet test` searches in the current folder for a `.csproj` or a `.sln` file. And then runs all tests connected to this solution (I wasn't aware of this magic until now ;-)

So yes, would be perfect if I can make `test-rerun mysolution.sln [OPTIONS]`

Thanks

**Comment by ricardofslp** [comment]
Hi @LMSSonos ,

That you should be able to do with the current version.

For that just provide in the argument the path to the folder where the solution or actually identify the solution.

One improvement we can do is search in the current folder if no argument is given.

So please try to call it identifying the path to the solution in the argument. If you have any difficulty just let us know.

Best Regards.

**Comment by LMSSonos** [comment]
HI @ricardofslp 

Yes, this worked as expected. Thanks for the hint. Out of curiosity, I run the following action after the run has been made to get a report about the failed tests. https://github.com/dorny/test-reporter - The thing is, that in the one .trx file where the run fails, I have the failed test, then it creates a second .trx file for the rerun and this contains the successful test. The test-reporter sees the same test twice, once as success, the other as failed and then the report will generate a report with failed tests.

In your code I saw that you keep track of the last files and also allow to delete all existing files. Im looking for an option/tool to remove the rerun (failed) test form the trx as it is shown in a next trx. 

Hope you could follow my issue ;-)
Thanks

**Comment by ricardofslp** [comment]
Hi @LMSSonos,

You would need, in this case, to just remove the failed from the old trx which would be a manipulation of the trx file.

Doing that goes a little bit out of scope of this tool. The remove of trx was included for the scenario where users don't want any trx file but since the tool needs it we have included that option.

As for your scenario I would say the best solution would be the report itself to have an option where when one pass is found then it is considered as a pass.

In the future I may work in another tool that merges two trx files and has that behavior.

Best Regards.

**Comment by LMSSonos** [comment]
Hi @ricardofslp 

No problem, I wrote a little c#-Script which makes the cleanup job. I'll share it if someone else needs it, so for me it's perfect.  I also would vote for #50 to pass the `-configuration` parameter to the tool, as I usually run them in `Release` and not debug.

Thanks again for all infos!

```
#! "netcoreapp6.0"

using System;
using System.IO;
using System.Linq;
using System.Xml;

var resultsFolder = "c:\\temp\\trx";

if (Args.Count > 0)
{
    resultsFolder = Args[0];
}

Console.WriteLine("Processing folder " + resultsFolder);

var trxFiles = new List<TrxFile>();
foreach (var file in new DirectoryInfo(resultsFolder).GetFiles("*.trx"))
{
    XmlDocument doc = new XmlDocument();
    doc.Load(file.FullName);
    XmlNodeList nodeList = doc.GetElementsByTagName("UnitTestResult");
    if (nodeList.Count == 0)
    {
        Console.WriteLine($"{file.Name} => empty - no tests found");
        file.MoveTo(file.FullName + ".no-tests");
        continue;
    }

    var trxFile = new TrxFile{ Name = file.FullName};
    trxFiles.Add(trxFile);

    Console.WriteLine($"{file.Name} => {nodeList.Count} tests found");
    foreach (XmlNode node in nodeList)
    {
        string testName = node.Attributes["testName"].Value;
        string outcome = node.Attributes["outcome"].Value;
        string duration = node.Attributes["duration"].Value;
        trxFile.TestResults.Add(new TestResult
        {
            TestName = testName,
            OutCome = outcome,
            EndTime = DateTime.Parse(node.Attributes["endTime"].Value)
        });
    }
}

var rerunTests = 0;
// check if we have failed
foreach(var trxFile in trxFiles.Where(x => x.TestResults.Any(y => y.OutCome == "Failed")))
{
    foreach(var test in trxFile.TestResults.Where(x => x.OutCome == "Failed"))
    {
        Console.WriteLine($"Failed test  {test.TestName} in file {trxFile.Name}");
        // check if we have another file with the same result but success
        var otherFile = trxFiles.FirstOrDefault(x => x.TestResults.Any(y => y.TestName == test.TestName && y.OutCome == "Passed"));
        if (otherFile != null)
        {
            Console.WriteLine($"Found passed in {otherFile.Name}");
            // remove node from failed file
            XmlDocument doc = new XmlDocument();
            doc.Load(trxFile.Name);
            XmlNode nodeToRemove = doc.SelectSingleNode($"//UnitTestResult[@testName='{test.TestName}']");
            nodeToRemove.ParentNode.RemoveChild(nodeToRemove);
            doc.Save(trxFile.Name);
            rerunTests++;
        }
    }
}

public class TrxFile
{
    public string Name { get; set; }
    public List<TestResult> TestResults { get; set; } = new List<TestResult>();
}

public class TestResult
{
    public string TestName { get; set; }
    public string OutCome { get; set; }
    public DateTime EndTime  { get; set; }
}
```

**Comment by ricardofslp** [comment]
Hi @LMSSonos,

I'm currently working on a tool that will do something similar to what you have posted before in fact. I will reply here in case you want to use it instead of the script (I will keep supporting that one).
Regarding the other improvement you've talked about I finish that development yesterday in this PR: https://github.com/joaoopereira/dotnet-test-rerun/pull/62

**Comment by ricardofslp** [comment]
Hi @LMSSonos ,

Sorry for the delay but I was unable to work in this until now.
But if you want you can start using this tool: https://www.nuget.org/packages/dotnet-trx-merge

You've the option to identify several files with -f (`trx-merge -f file1 -f file2`) or with -d to identify a directory (with or without the recursive flag)

We will keep providing support this tool also.
