### ISSUE TITLE
Test Reruns don't seem to be specific to framework version

### ISSUE THREAD

**Issue by samholder** [joaoopereira/dotnet-test-rerun#89]
Hi.

I think there is some issue with the rerun logic when tests target multiple frameworks, because it doesn't just rerun the test in the framework it failed in, it reruns them both.

I created a simple test project with this content:

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
     #if NET7_0
            Assert.IsTrue(true);
     #else
            Assert.IsTrue(false);
      #endif
         }
      } 
      
     and when I run the tests I get this output:
     
     

> Determining projects to restore...
>     All projects are up-to-date for restore.
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v6.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>     Failed TestMethod1 [19 ms]
>     Error Message:
>      Assert.IsTrue failed.
>     Stack Trace:
>        at MultiFrameworkTest.UnitTest1.TestMethod1() in C:\Users\sam.holder\source\repos\MultiFrameworkTest\UnitTest1.cs:line 12
> 
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_16.trx
> 
>   Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 30 ms - MultiFrameworkTest.dll (net6.0)
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v7.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_17.trx
> 
>   Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 9 ms - MultiFrameworkTest.dll (net7.0)
> 
> 
>   No tests found with the Outcome Failed in file sam.holder_CW-LAP-SAM2_2023-10-23_15_28_17.trx
>   Rerun attempt 1/3
>   Found Failed tests: FullyQualifiedName~MultiFrameworkTest.UnitTest1.TestMethod1
>   Rerun filter: FullyQualifiedName~MultiFrameworkTest.UnitTest1.TestMethod1
>     Determining projects to restore...
>     All projects are up-to-date for restore.
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v6.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>     Failed TestMethod1 [15 ms]
>     Error Message:
>      Assert.IsTrue failed.
>     Stack Trace:
>        at MultiFrameworkTest.UnitTest1.TestMethod1() in C:\Users\sam.holder\source\repos\MultiFrameworkTest\UnitTest1.cs:line 12
> 
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_19.trx
> 
>   Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 26 ms - MultiFrameworkTest.dll (net6.0)
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v7.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_20.trx
> 
>   Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 9 ms - MultiFrameworkTest.dll (net7.0)
> 
> 
>   No tests found with the Outcome Failed in file sam.holder_CW-LAP-SAM2_2023-10-23_15_28_20.trx
>   Rerun attempt 2/3
>   Found Failed tests: FullyQualifiedName~MultiFrameworkTest.UnitTest1.TestMethod1
>   Rerun filter: FullyQualifiedName~MultiFrameworkTest.UnitTest1.TestMethod1
>     Determining projects to restore...
>     All projects are up-to-date for restore.
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v6.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>     Failed TestMethod1 [15 ms]
>     Error Message:
>      Assert.IsTrue failed.
>     Stack Trace:
>        at MultiFrameworkTest.UnitTest1.TestMethod1() in C:\Users\sam.holder\source\repos\MultiFrameworkTest\UnitTest1.cs:line 12
> 
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_23.trx
> 
>   Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 28 ms - MultiFrameworkTest.dll (net6.0)
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v7.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_24.trx
> 
>   Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 9 ms - MultiFrameworkTest.dll (net7.0)
> 
> 
>   No tests found with the Outcome Failed in file sam.holder_CW-LAP-SAM2_2023-10-23_15_28_24.trx
>   Rerun attempt 3/3
>   Found Failed tests: FullyQualifiedName~MultiFrameworkTest.UnitTest1.TestMethod1
>   Rerun filter: FullyQualifiedName~MultiFrameworkTest.UnitTest1.TestMethod1
>     Determining projects to restore...
>     All projects are up-to-date for restore.
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll
>     MultiFrameworkTest -> C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net6.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v6.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>     Failed TestMethod1 [14 ms]
>     Error Message:
>      Assert.IsTrue failed.
>     Stack Trace:
>        at MultiFrameworkTest.UnitTest1.TestMethod1() in C:\Users\sam.holder\source\repos\MultiFrameworkTest\UnitTest1.cs:line 12
> 
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_26.trx
> 
>   Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 25 ms - MultiFrameworkTest.dll (net6.0)
>   Test run for C:\Users\sam.holder\source\repos\MultiFrameworkTest\bin\Debug\net7.0\MultiFrameworkTest.dll (.NETCoreApp,Version=v7.0)
>   Microsoft (R) Test Execution Command Line Tool Version 17.6.0 (x64)
>   Copyright (c) Microsoft Corporation.  All rights reserved.
> 
>   Starting test execution, please wait...
>   A total of 1 test files matched the specified pattern.
>   Results File: C:\Users\sam.holder\source\repos\MultiFrameworkTest\sam.holder_CW-LAP-SAM2_2023-10-23_15_28_27.trx
> 
>   Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 9 ms - MultiFrameworkTest.dll (net7.0)

As you can see even though the test only fails in .net 6.0 its rerun in 7.0 every time as well.

I think you can provide the `--framework` option to `dotnet test` so maybe we should parse the framework out of the path for the test results in the trx and use that to rerun only the failing tests

**Comment by ricardofslp** [comment]
Hi @samholder ,

Thanks for reporting this. We will try to see a way to make this work.
It may force us to change the way we trigger the rerun a little bit.

**Comment by samholder** [comment]
I have started on a fix, https://github.com/joaoopereira/dotnet-test-rerun/pull/90 this is work in progress and currently has failing tests, but should outline the approach I think we could take. Happy to get early feedback here, but have a busy day today and might not get much more done on this until later in the week. I'll try and push updates frequently if I have them

**Comment by ricardofslp** [comment]
Hi @samholder,

I was already working on one also. Should be able to finish it today.

Just want to improve the coverage a little bit before releasing an alpha.
I will release one with the PR still open for you to test if you can.

Is that ok?

**Comment by samholder** [comment]
sounds good! thanks

**Comment by ricardofslp** [comment]
Please test with this version: https://www.nuget.org/packages/dotnet-test-rerun/1.7.0-alpha.0

**Comment by samholder** [comment]
yep this looks good, and seems to work for me! thanks a lot

**Comment by ricardofslp** [comment]
This fix was released officially with version 1.7.0  (https://www.nuget.org/packages/dotnet-test-rerun/1.7.0)
