### ISSUE TITLE
Allow multiple logger arguments

### ISSUE THREAD

**Issue by Silv-1** [joaoopereira/dotnet-test-rerun#94]
Executing

```
test-rerun --logger trx --logger logger2
```

Returns error

```
Option '--logger' expects a single argument but 2 were provided.
```

`dotnet test` would allow to provide multiple logger arguments.

**Comment by ricardofslp** [comment]
Hi @Silv-1,

Thanks for creating this issue.
We will try to work on this during this week.

**Comment by ricardofslp** [comment]
Hi @Silv-1,

Did this work in the alpha version?

**Comment by Silv-1** [comment]
Multiple `--logger` arguments worked.

Tested https://www.nuget.org/packages/dotnet-test-rerun/1.8.0-alpha.2.

Thank you very much. 🙏

**Comment by ricardofslp** [comment]
Released this officially in version https://www.nuget.org/packages/dotnet-test-rerun/1.8.0
Please test and close the issue if everything is as expected

**Comment by Silv-1** [comment]
Works in the official release.

Tested https://www.nuget.org/packages/dotnet-test-rerun/1.8.0.
